/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_TimeStampFinder_NDK */

#ifndef _Included_com_example_TimeStampFinder_NDK
#define _Included_com_example_TimeStampFinder_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_TimeStampFinder_NDK
 * Method:    scanning
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_TimeStampFinder_NDK_scanning
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_TimeStampFinder_NDK
 * Method:    decode_audio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_TimeStampFinder_NDK_decode_1audio
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_TimeStampFinder_NDK
 * Method:    decode_video
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_TimeStampFinder_NDK_decode_1video
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
